Class {
	#name : 'PNRRFruitMBitCoinBFS',
	#superclass : 'Object',
	#instVars : [
		'distances',
		'layers'
	],
	#category : 'PNRRCN4-UrbanMobility-DLT Fruit - Bitcoin',
	#package : 'PNRRCN4-UrbanMobility',
	#tag : 'DLT Fruit - Bitcoin'
}

{ #category : 'accessing' }
PNRRFruitMBitCoinBFS >> distances [

	^ distances
]

{ #category : 'accessing' }
PNRRFruitMBitCoinBFS >> distances: anObject [

	distances := anObject
]

{ #category : 'accessing' }
PNRRFruitMBitCoinBFS >> layers [

	^ layers
]

{ #category : 'accessing' }
PNRRFruitMBitCoinBFS >> layers: anObject [

	layers := anObject
]
