
echo:
	echo "Usage: make run"

batch:
	time cargo run --release --bin batch -- ../data/transport/florence/edges.csv ../data/transport/florence/requests_K10747_N30965.csv 1 > ../data/transport/florence/analysis.csv
	
single:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 0.1 Adelaide > ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 0.1 Belfast >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 0.1 Berlin >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 0.1 Bordeaux >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 0.1 Brisbane >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 0.1 Canberra >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 0.1 Detroit >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 0.1 Dublin >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 0.1 Grenoble >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 0.1 Helsinki >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 0.1 Kuopio >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 0.1 Lisbon >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 0.1 Luxembourg >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 0.1 Melbourne >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 0.1 Nantes >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 0.1 Palermo >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 0.1 Paris >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 0.1 Prague >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 0.1 Rennes >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 0.1 Rome >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 0.1 Sydney >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 0.1 Toulouse >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 0.1 Turku >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 0.1 Venice >> ../data/transport/single.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 0.1 Winnipeg >> ../data/transport/single.csv

single-1:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 1 Adelaide > ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 1 Belfast >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 1 Berlin >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 1 Bordeaux >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 1 Brisbane >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 1 Canberra >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 1 Detroit >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 1 Dublin >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 1 Grenoble >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 1 Helsinki >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 1 Kuopio >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 1 Lisbon >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 1 Luxembourg >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 1 Melbourne >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 1 Nantes >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 1 Palermo >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 1 Paris >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 1 Prague >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 1 Rennes >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 1 Rome >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 1 Sydney >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 1 Toulouse >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 1 Turku >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 1 Venice >> ../data/transport/single-1.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 1 Winnipeg >> ../data/transport/single-1.csv

single-100:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 100 Adelaide > ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 100 Belfast >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 100 Berlin >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 100 Bordeaux >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 100 Brisbane >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 100 Canberra >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 100 Detroit >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 100 Dublin >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 100 Grenoble >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 100 Helsinki >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 100 Kuopio >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 100 Lisbon >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 100 Luxembourg >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 100 Melbourne >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 100 Nantes >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 100 Palermo >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 100 Paris >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 100 Prague >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 100 Rennes >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 100 Rome >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 100 Sydney >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 100 Toulouse >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 100 Turku >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 100 Venice >> ../data/transport/single-100.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 100 Winnipeg >> ../data/transport/single-100.csv

single-300:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 300 Adelaide > ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 300 Belfast >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 300 Berlin >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 300 Bordeaux >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 300 Brisbane >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 300 Canberra >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 300 Detroit >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 300 Dublin >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 300 Grenoble >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 300 Helsinki >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 300 Kuopio >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 300 Lisbon >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 300 Luxembourg >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 300 Melbourne >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 300 Nantes >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 300 Palermo >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 300 Paris >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 300 Prague >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 300 Rennes >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 300 Rome >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 300 Sydney >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 300 Toulouse >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 300 Turku >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 300 Venice >> ../data/transport/single-300.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 300 Winnipeg >> ../data/transport/single-300.csv

single-500:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 500 Adelaide > ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 500 Belfast >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 500 Berlin >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 500 Bordeaux >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 500 Brisbane >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 500 Canberra >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 500 Detroit >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 500 Dublin >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 500 Grenoble >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 500 Helsinki >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 500 Kuopio >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 500 Lisbon >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 500 Luxembourg >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 500 Melbourne >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 500 Nantes >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 500 Palermo >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 500 Paris >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 500 Prague >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 500 Rennes >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 500 Rome >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 500 Sydney >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 500 Toulouse >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 500 Turku >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 500 Venice >> ../data/transport/single-500.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 500 Winnipeg >> ../data/transport/single-500.csv


single-1000:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 1000 Adelaide > ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 1000 Belfast >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 1000 Berlin >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 1000 Bordeaux >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 1000 Brisbane >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 1000 Canberra >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 1000 Detroit >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 1000 Dublin >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 1000 Grenoble >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 1000 Helsinki >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 1000 Kuopio >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 1000 Lisbon >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 1000 Luxembourg >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 1000 Melbourne >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 1000 Nantes >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 1000 Palermo >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 1000 Paris >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 1000 Prague >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 1000 Rennes >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 1000 Rome >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 1000 Sydney >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 1000 Toulouse >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 1000 Turku >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 1000 Venice >> ../data/transport/single-1000.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 1000 Winnipeg >> ../data/transport/single-1000.csv


single-1124:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv 1 1124 Adelaide > ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv 1 1124 Belfast >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv 1 1124 Berlin >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv 1 1124 Bordeaux >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv 1 1124 Brisbane >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv 1 1124 Canberra >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv 1 1124 Detroit >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv 1 1124 Dublin >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv 1 1124 Grenoble >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv 1 1124 Helsinki >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv 1 1124 Kuopio >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv 1 1124 Lisbon >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv 1 1124 Luxembourg >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv 1 1124 Melbourne >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv 1 1124 Nantes >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv 1 1124 Palermo >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv 1 1124 Paris >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv 1 1124 Prague >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv 1 1124 Rennes >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv 1 1124 Rome >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv 1 1124 Sydney >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv 1 1124 Toulouse >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv 1 1124 Turku >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv 1 1124 Venice >> ../data/transport/single-1124.csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv 1 1124 Winnipeg >> ../data/transport/single-1124.csv

single-generic:
	time cargo run --release --bin single -- ../data/transport/adelaide/edges.csv ../data/transport/adelaide/requests_K75480_N754800.csv  $(REPS) $(K) Adelaide > ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/belfast/edges.csv ../data/transport/belfast/requests_K19170_N191700.csv  $(REPS) $(K) Belfast >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/berlin/edges.csv ../data/transport/berlin/requests_K46010_N460100.csv  $(REPS) $(K) Berlin >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/bordeaux/edges.csv ../data/transport/bordeaux/requests_K34350_N343500.csv  $(REPS) $(K) Bordeaux >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/brisbane/edges.csv ../data/transport/brisbane/requests_K96450_N964500.csv  $(REPS) $(K) Brisbane >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/canberra/edges.csv ../data/transport/canberra/requests_K27640_N276400.csv  $(REPS) $(K) Canberra >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/detroit/edges.csv ../data/transport/detroit/requests_K56830_N568300.csv  $(REPS) $(K) Detroit >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/dublin/edges.csv ../data/transport/dublin/requests_K45710_N457100.csv  $(REPS) $(K) Dublin >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/grenoble/edges.csv ../data/transport/grenoble/requests_K15470_N154700.csv  $(REPS) $(K) Grenoble >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/helsinki/edges.csv ../data/transport/helsinki/requests_K69860_N698600.csv  $(REPS) $(K) Helsinki >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/kuopio/edges.csv ../data/transport/kuopio/requests_K5490_N54900.csv  $(REPS) $(K) Kuopio >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/lisbon/edges.csv ../data/transport/lisbon/requests_K70730_N707300.csv  $(REPS) $(K) Lisbon >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/luxembourg/edges.csv ../data/transport/luxembourg/requests_K13670_N136700.csv  $(REPS) $(K) Luxembourg >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/melbourne/edges.csv ../data/transport/melbourne/requests_K194930_N1949300.csv  $(REPS) $(K) Melbourne >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/nantes/edges.csv ../data/transport/nantes/requests_K23530_N235300.csv  $(REPS) $(K) Nantes >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/palermo/edges.csv ../data/transport/palermo/requests_K21760_N217600.csv  $(REPS) $(K) Palermo >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/paris/edges.csv ../data/transport/paris/requests_K11950_N1195000.csv  $(REPS) $(K) Paris >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/prague/edges.csv ../data/transport/prague/requests_K51470_N514700.csv  $(REPS) $(K) Prague >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/rennes/edges.csv ../data/transport/rennes/requests_K14070_N140700.csv  $(REPS) $(K) Rennes >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/rome/edges.csv ../data/transport/rome/requests_K78690_N786900.csv  $(REPS) $(K) Rome >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/sydney/edges.csv ../data/transport/sydney/requests_K240630_N2406300.csv  $(REPS) $(K) Sydney >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/toulouse/edges.csv ../data/transport/toulouse/requests_K33290_N332900.csv  $(REPS) $(K) Toulouse >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/turku/edges.csv ../data/transport/turku/requests_K18500_N185000.csv  $(REPS) $(K) Turku >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/venice/edges.csv ../data/transport/venice/requests_K18740_N187400.csv  $(REPS) $(K) Venice >> ../data/transport/single-$(REPS)-$(K).csv
	time cargo run --release --bin single -- ../data/transport/winnipeg/edges.csv ../data/transport/winnipeg/requests_K50790_N507900.csv  $(REPS) $(K) Winnipeg >> ../data/transport/single-$(REPS)-$(K).csv

single-par:
	REPS=1 K=1124 make single-generic &
	REPS=10 K=1124 make single-generic &
	REPS=100 K=1124 make single-generic &	
	REPS=500 K=1124 make single-generic &
	REPS=1000 K=1124 make single-generic &
	REPS=5000 K=1124 make single-generic &
	REPS=10000 K=1124 make single-generic &
	REPS=50000 K=1124 make single-generic &
	REPS=100000 K=1124 make single-generic &


single-all: single-1 single-100 single-300 single-500 single-1000

full:
	time cargo run --release --bin rust -- ../data/transport/florence/edges.csv ../data/transport/florence/requests_K10747_N30965.csv 0.1 50 300 > ../data/transport/florence/analysis-0.1e-50reps-300s.txt
